# Generated by Django 5.1 on 2025-01-31 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letrasRotinas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letras',
            old_name='letra',
            new_name='centro',
        ),
    ]
