# Generated by Django 5.1 on 2024-08-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_rpa', models.TextField()),
                ('status', models.IntegerField()),
                ('horario', models.DateTimeField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('exception', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
