# Generated by Django 5.1 on 2024-08-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='nome_agente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='nome_pc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
