# Generated by Django 5.1 on 2024-08-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_logs', '0002_registro_nome_agente_registro_nome_pc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('log.user', 'Permissão para Usuario Simples'), ('log.admin', 'Permissão para Usuario ADMIN')),
            },
        ),
    ]
