# Generated by Django 5.1 on 2025-05-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_logs', '0003_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='ia_analise',
            field=models.TextField(blank=True, null=True),
        ),
    ]
