# Generated by Django 5.1 on 2024-09-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('tasks', 'Permissão para acessar a pagina das task permissão obrigatoria'), ('tasks.pagamentos_diarios', 'Permissão para acessar a Task de Pagamandos Diarios'), ('tasks.atualizar_dashboard', 'Permissão para acessar a Task de Atualização de DashBoard automatica'), ('tasks.zenlink', 'Permissão para acessar a Task ddo Conector do app de retenção tecnica com o Zendesk')),
            },
        ),
    ]
