# Generated by Django 5.1 on 2024-09-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': (('tasks', 'Permissão para acessar a pagina das task permissão obrigatoria'), ('pagamentos_diarios', 'Permissão para acessar a Task de Pagamandos Diarios'), ('atualizar_dashboard', 'Permissão para acessar a Task de Atualização de DashBoard automatica'), ('zenlink', 'Permissão para acessar a Task ddo Conector do app de retenção tecnica com o Zendesk'))},
        ),
    ]
