# Generated by Django 5.1 on 2024-09-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_permissions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': (('tasks', 'Permissão para acessar a pagina das task permissão obrigatoria'), ('pagamentos_diarios', 'Permissão para acessar a Task de Pagamandos Diarios'), ('atualizar_dashboard', 'Permissão para acessar a Task de Atualização de DashBoard automatica'), ('zenlink', 'Permissão para acessar a Task ddo Conector do app de retenção tecnica com o Zendesk'), ('teste', 'Permissão para acessar o teste do TASKS'))},
        ),
    ]
