# Generated by Django 5.1 on 2024-09-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_permissions_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.TextField()),
                ('permission', models.TextField()),
                ('can_stop', models.BooleanField(default=False)),
                ('infor', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
