# Generated by Django 5.1 on 2024-09-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tarefas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='can_stop',
            field=models.BooleanField(default=True),
        ),
    ]
