# Generated by Django 5.1 on 2024-10-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tarefas_can_stop'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroExec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('nome_tarefa', models.TextField()),
                ('data_exec', models.DateTimeField()),
            ],
        ),
    ]
